[project]
name = "now-engine"
version = "0.1.0"
description = "multimodal RAG agent"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ollama>=0.4.7",
    "pdfplumber>=0.11.5",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.0.1",
    "tabulate>=0.9.0",
]
